
export const COMUNES_CARGANDO_PAGINA = 'COMUNES_CARGANDO_PAGINA'
export const COMUNES_MOSTRAR_MENU = 'COMUNES_MOSTRAR_MENU'
export const COMUNES_CARGANDO_PAGINA_INICIO = 'COMUNES_CARGANDO_PAGINA_INICIO'