// REQUEST
export const ESTADO_REQUEST_EXITO           = 'ESTADO_REQUEST_EXITO'
export const ESTADO_REQUEST_NO_AUTORIZADO   = 'ESTADO_REQUEST_NO_AUTORIZADO'
export const ESTADO_REQUEST_NO_EXISTE       = 'ESTADO_REQUEST_NO_EXISTE'
export const ESTADO_REQUEST_ERROR_SERVIDOR  = 'ESTADO_REQUEST_ERROR_SERVIDOR'
export const ESTADO_REQUEST_DESCONOCIDO     = 'ESTADO_REQUEST_DESCONOCIDO'
